#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="mongo"
check_container_initialized
check_service_initialized init
chown -R 777 /var/log/mongodb
rm -rf /var/run/mongodb/*
exec mongod --unixSocketPrefix=/var/run/mongodb --config /etc/mongodb.conf run
