#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="cron"

### Set Defaults
ENABLE_CRON=${ENABLE_CRON:-"TRUE"}

### Check to see if Enabled/Disabled
if [ "$ENABLE_CRON" = "FALSE" ] || [ "$ENABLE_CRON" = "false" ];  then
        print_notice "Disabling Cron"
        service_stop `basename $0`
fi

print_debug "Creating Cron Folder"
silent mkdir -p /var/spool/cron

liftoff
