#!/usr/bin/with-contenv bash

cat <<EOF >> /etc/fail2ban/jail.conf

[asterisk-iptables]
enabled  = true
filter   = asterisk
logpath  = /var/log/asterisk/messages
maxretry = 3
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK, protocol=all]
           sendmail-whois[name=ASTERISK, dest=root, sender=fail2ban@asterisk]
ignoreip = 127.0.0.1/8

[asterisk-security-iptables]
enabled  = true
filter   = asterisk-security
logpath  = /var/log/asterisk/security
maxretry = 3
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK-security, protocol=all]
           sendmail-whois[name=ASTERISK-security, dest=root, sender=fail2ban@asterisk]
ignoreip = 127.0.0.1/8
EOF

  mkdir -p /tmp/state
  touch /tmp/state/04-fail2ban-init
