#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service single
# shellcheck disable=SC2034
PROCESS_NAME="fail2ban"

if var_true "$ENABLE_FAIL2BAN" ;  then
	sed -i -e "s/logtarget = \/var\/log\/fail2ban.log/logtarget = \/var\/log\/fail2ban\/fail2ban.log/g" /etc/fail2ban/fail2ban.conf
	rm -rf /etc/fail2ban/jail.d/*
	mkdir -p /var/log/asterisk/
	mkdir -p /var/log/fail2ban/
	touch /var/log/asterisk/full
  touch /var/log/asterisk/freepbx_security.log
	cat <<EOF > /etc/fail2ban/jail.conf

#[asterisk-iptables]
#backend = auto
#enabled  = true
#filter   = asterisk
#logpath  = /var/log/asterisk/full
#maxretry = 3
#bantime = 86400
#findtime = 3600
#action   = iptables-allports[name=ASTERISK, protocol=all]
#ignoreip = 127.0.0.1/8

[asterisk-security-iptables]
backend = auto
enabled  = true
filter   = asterisk-security
logpath  = /var/log/asterisk/full
maxretry = 5
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK-security, protocol=all]
ignoreip = 127.0.0.1/8

[freepbx-iptables]
backend = auto
enabled  = true
filter   = asterisk
logpath  = /var/log/asterisk/freepbx_security.log
maxretry = 5
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK, protocol=all]
ignoreip = 127.0.0.1/8
EOF

	print_info "Starting Fail2ban"
	silent service fail2ban start
fi

liftoff