#!/usr/bin/with-contenv bash

rm -rf /etc/fail2ban/jail.d/*
mkdir -p /var/log/asterisk/
touch /var/log/asterisk/full
cat <<EOF > /etc/fail2ban/jail.conf

[asterisk-iptables]
backend = auto
enabled  = true
filter   = asterisk
logpath  = /var/log/asterisk/full
maxretry = 3
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK, protocol=all]
ignoreip = 127.0.0.1/8

[asterisk-security-iptables]
backend = auto
enabled  = true
filter   = asterisk-security
logpath  = /var/log/asterisk/full
maxretry = 3
bantime = 86400
findtime = 3600
action   = iptables-allports[name=ASTERISK-security, protocol=all]
ignoreip = 127.0.0.1/8
EOF

echo ''
echo '** [fail2ban] Starting Fail2ban'
service fail2ban start

  mkdir -p /tmp/state
  touch /tmp/state/04-fail2ban-init
