#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="mongo"

if [[ "$ENABLE_XMPP" = "TRUE" ]] || [[ "$ENABLE_XMPP" = "true" ]];  then
	print_notice "Enabling MongoDB for XMPP support"
    mkdir -p /var/log/mongodb
    touch /var/log/mongodb/mongodb.log
    mkdir -p /data/var/lib/mongodb
    service_start /var/run/s6/services/08-mongodb
else
	service_stop 08-mongodb	 
fi

liftoff