#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service single

PROCESS_NAME="mongo"

if var_true $ENABLE_XMPP ; then
	print_notice "Enabling MongoDB for XMPP support"
    mkdir -p /var/log/mongodb
    touch /var/log/mongodb/mongodb.log
    mkdir -p /data/var/lib/mongodb
    service_start /var/run/s6/services/08-mongodb
else
	service_stop 08-mongodb	 
fi

liftoff