#!/usr/bin/with-contenv bash

s6-svc -d /var/run/s6/services/08-mongodb

ENABLE_XMPP=${ENABLE_XMPP:-"FALSE"}

if [[ "$ENABLE_XMPP" = "TRUE" ]] || [[ "$ENABLE_XMPP" = "true" ]];  then
	echo '** [mongodb] Enabling MongoDB for XMPP support'
        s6-svc -u /var/run/s6/services/08-mongodb   
fi

mkdir -p /tmp/state
touch /tmp/state/08-mongodb-init
