#!/usr/bin/with-contenv bash

# shellcheck disable=SC1090
for s in /assets/functions/*; do source "$s"; done
# shellcheck disable=SC2034
PROCESS_NAME="mariadb"

if var_true "$DB_EMBEDDED" ;  then
  silent service mysql stop
  mkdir -p /var/lib/mysql

  if [ ! -d /var/lib/mysql/mysql ]; then
    print_info "New embedded database detected, setting up.."
    cp -R /assets/config/var/lib/mysql/* /var/lib/mysql
  fi

  chown -R mysql. /var/lib/mysql
  silent service mysql start
fi

liftoff