#!/usr/bin/with-contenv bash
  
  mkdir -p /var/lib/mysql


  if [ ! -f /var/lib/mysql/database ]; then
    echo '** [mysql] New Database Detected, setting up..'
    cp -R /assets/config/var/lib/mysql/* /var/lib/mysql
  fi

  chown -R mysql:mysql /var/lib/mysql 
  /etc/init.d/mysql restart

  mkdir -p /tmp/state
  touch /tmp/state/10-mariadb-init
