#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  PHP_TIMEOUT=${PHP_TIMEOUT:-"600"}
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/nginx/conf.d/default.conf
  
### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

### Sanity Test
if [ ! -n "DB_HOST" ]; then
    echo '** [freepbx] ERROR: No Database Host Entered! '
    exit 1
fi

if [ ! -n "DB_NAME" ]; then
    echo '** [freepbx] ERROR: No Database Pass Entered! '
    exit 1
fi

if [ ! -n "DB_USER" ]; then
    echo '** [freepbx] ERROR: No Database User Entered! '
    exit 1
fi

if [ ! -n "DB_PASS" ]; then
    echo '** [freepbx] ERROR: No Database Pass Entered! '
    exit 1
fi

### Set Defaults
DB_PORT=${DB_PORT:-3306}
RTP_START=${RTP_START:-18000}
RTP_END=${RTP_END:-20000}


### Make sure that DB is accessible
while true; do
	mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
	out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
	echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
	if [ $? -eq 0 ]; then
    	echo "** [freepbx] DB Server is available !"
    	break
	fi
	echo "** [freepbx] DB Server unavailable, sleeping a little bit ..."
	sleep 2
done

if [ ! -f /data/.initialized ]; then
    echo '** [freepbx] Creating Default Configuration Files'
	cp -R /assets/config/* /data/
fi

echo '** [freepbx] Setting File Permissions'
mkdir -p /data/etc/asterisk
mkdir -p /data/var/lib/asterisk/{agi-bin,bin,playback}
mkdir -p /data/var/spool/asterisk/{dictate,meetme,monitor,recording,system,tmp,voicemail}
mkdir -p /data/var/run/asterisk
mkdir -p /www/logs/asterisk
chown -R asterisk:asterisk /data
chown -R asterisk:asterisk /www/logs/asterisk

### Check if FreePBX Installed
if [ ! -f /www/freepbx/index.php ]; then
	echo '** [freepbx] New Install Detected - Please wait while we fetch FreePBX...'
cat <<EOF > /etc/odbc.ini
[asteriskcdrdb]
Description = MySQL connection to 'asteriskcdrdb' database
driver = MySQL
server = $DB_HOST
User = $DB_USER
Password = $DB_PASS
database = $DB_NAME
Port = $DB_PORT
option = 3
EOF
   	cd /usr/src
   	git clone -b release/14.0 --single-branch https://github.com/FreePBX/framework.git freepbx >/dev/null 2>&1
   	cd /usr/src/freepbx
   	cp -R /etc/odbc.ini /usr/src/freepbx/installlib/files/odbc.ini
   	./start_asterisk start 
	sed -i -e "s/\$amp_conf\['AMPDBHOST'\] = 'localhost';/\$amp_conf\['AMPDBHOST'\] = '$DB_HOST';/g" /usr/src/freepbx/installlib/installcommand.class.php
	sed -i -e "s/\$amp_conf\['CDRDBNAME'\] : 'asteriskcdrdb',/\$amp_conf\['CDRDBNAME'\] : '$DB_NAME',/g" /usr/src/freepbx/installlib/installcommand.class.php
	sed -i -e "s/\$amp_conf\['CDRDBNAME'\] : 'asteriskcdrdb',/\$amp_conf\['CDRDBNAME'\] : '$DB_NAME',/g" /usr/src/freepbx/amp_conf/htdocs/admin/bootstrap.php

	echo '** [freepbx] Installing FreePBX'
	./install -n --dbuser=$DB_USER --dbpass=$DB_PASS --dbname=$DB_NAME --cdrdbname=$DB_NAME --webroot=/www/freepbx
cat <<EOF > /etc/freepbx.conf
<?php
\$amp_conf['AMPDBUSER'] = '$DB_USER';
\$amp_conf['AMPDBPASS'] = '$DB_PASS';
\$amp_conf['AMPDBHOST'] = '$DB_HOST';
\$amp_conf['AMPDBNAME'] = '$DB_NAME';
\$amp_conf['AMPDBENGINE'] = 'mysql';
\$amp_conf['CDRDBNAME'] = '$DB_NAME';
\$amp_conf['CDRDBHOST'] = '$DB_HOST';
\$amp_conf['CDRDBNAME'] = '$DB_NAME';
\$amp_conf['CDRDBUSER'] = '$DB_USER';
\$amp_conf['CDRDBPASS'] = '$DB_PASS';
\$amp_conf['CDRDBTYPE'] = 'mysql';
require_once('/www/freepbx/admin/bootstrap.php');
?>
EOF
   	echo '** [freepbx] Enabling Default Modules'
	fwconsole ma upgrade framework core 
	fwconsole ma download cdr
	# CDR Hack
    mysql -u$DB_USER -p$DB_PASS -h$DB_HOST asterisk < /usr/src/freepbx/installlib/SQL/cdr.sql
    mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; UPDATE freepbx_settings SET `value` = "'$DB_HOST'" WHERE keyword = "CDRDBHOST"; UPDATE freepbx_settings SET `value` = "'$DB_NAME'" WHERE keyword = "CDRDBNAME"; UPDATE freepbx_settings SET `value` = "'$DB_PASS'" WHERE keyword = "CDRDBPASS"; UPDATE freepbx_settings SET `value` = "'$DB_USER'" WHERE keyword = "CDRDBUSER"; UPDATE freepbx_settings SET `value` = "mysql" WHERE keyword = "CDRDBTYPE"; UPDATE freepbx_settings SET `value` = "'$DB_PORT'" WHERE keyword = "CDRDBPORT"; UPDATE freepbx_settings SET `value` = "cdr" WHERE keyword = "CDRDBTABLENAME";'
	cp -R /www/freepbx/admin/modules/cdr/install.php /www/freepbx/admin/modules/cdr/.install.php
	sed -i -e 's/\$db_host = !empty(\$db_host) ? \$db_host : "localhost";/\$db_host = !empty(\$db_host) ? \$db_host : "'$DB_HOST'";/g' /www/freepbx/admin/modules/cdr/install.php
	sed -i -e 's/\$db_name = !empty(\$db_name) ? \$db_name : "asteriskcdrdb";/\$db_name = !empty(\$db_name) ? \$db_name : "'$DB_NAME'";/g' /www/freepbx/admin/modules/cdr/install.php
	fwconsole ma install cdr
	cp -R /www/freepbx/admin/modules/cdr/.install.php /www/freepbx/admin/modules/cdr/install.php
	fwconsole ma upgrade voicemail sipsettings infoservices featurecodeadmin logfiles callrecording dashboard music conferences 
	fwconsole chown 
	fwconsole reload 
	fwconsole restart
	fwconsole stop
	cd / 
	rm -rf /usr/src/freepbx
	touch /data/.installed
fi

### Data Persistence Workaround
  if [ ! -f /usr/sbin/fwconsole ]; then
  	   ln -s /var/lib/asterisk/bin/fwconsole /usr/sbin/fwconsole
  fi

  if [ ! -f /usr/sbin/amportal ]; then
  	   ln -s /var/lib/asterisk/bin/amportal /usr/sbin/amportal
  fi
  
  if [ ! -f /data/etc/amportal.conf ]; then
  		mkdir -p /data/etc/
	  	cp -R /etc/amportal.conf /data/etc/
	  	rm -rf /etc/amportal.conf
	  	touch /data/etc/amportal.conf
	  	chown asterisk:asterisk /data/etc/amportal.conf
	  	ln -s /data/etc/amportal.conf /etc/amportal.conf
  else
	  	ln -s /data/etc/amportal.conf /etc/amportal.conf
	  	touch /data/etc/amportal.conf
  fi


### Setup Dynamic Configuration
echo '** [freepbx] Setting Configuration'
cat <<EOF > /etc/freepbx.conf
<?php
\$amp_conf['AMPDBUSER'] = '$DB_USER';
\$amp_conf['AMPDBPASS'] = '$DB_PASS';
\$amp_conf['AMPDBHOST'] = '$DB_HOST';
\$amp_conf['AMPDBNAME'] = '$DB_NAME';
\$amp_conf['AMPDBENGINE'] = 'mysql';
\$amp_conf['CDRDBNAME'] = '$DB_NAME';
\$amp_conf['CDRDBHOST'] = '$DB_HOST';
\$amp_conf['CDRDBNAME'] = '$DB_NAME';
\$amp_conf['CDRDBUSER'] = '$DB_USER';
\$amp_conf['CDRDBPASS'] = '$DB_PASS';
\$amp_conf['CDRDBTYPE'] = 'mysql';
require_once('/www/freepbx/admin/bootstrap.php');
?>
EOF

cat <<EOF > /etc/odbc.ini
[asteriskcdrdb]
Description = MySQL connection to 'asteriskcdrdb' database
driver = MySQL
server = $DB_HOST
User = $DB_USER
Password = $DB_PASS
database = $DB_NAME
Port = $DB_PORT
option = 3
EOF

if [ ! -f /etc/asterisk/cdr_adaptive_odbc.conf ]; then
	cat <<EOF > /etc/asterisk/cdr_adaptive_odbc.conf
[first]
connection=asteriskcdrdb
table=cdr
alias start => calldate
EOF
fi

chown asterisk:asterisk /etc/freepbx.conf

### Set RTP Ports
echo '** [freepbx] Set RTP Ports' 
mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; UPDATE sipsettings SET `data` = "'$RTP_START'" WHERE keyword = "rtpstart";  UPDATE sipsettings SET `data` = "'$RTP_FINISH'" WHERE keyword = "rtpend";'

### Fix a Freepbx bug with upgrades
mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; ALTER TABLE featurecodes CHANGE column helptext helptext VARCHAR(10000);'

echo '** [freepbx] Starting Asterisk]'
fwconsole chown > /dev/null 2>&1
fwconsole start > /dev/null 2>&1
fwconsole reload > /dev/null 2>&1

 mkdir -p /tmp/state
 touch /tmp/state/10-freepbx-init
