#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/04-fail2ban-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/04-fail2ban ]; then
	touch auth.log
fi

echo ''
echo '** [fail2ban] Starting Fail2ban'
exec fail2ban-server -f;
