#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service single

if var_true "$ENABLE_XMPP" ;  then
  silent mongod --unixSocketPrefix=/var/run/mongodb --config /etc/mongod.conf --shutdown
  rm -f /tmp/.container/*-mongo*
fi