#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service

if var_true "$ENABLE_XMPP" ;  then
    mongod --unixSocketPrefix=/var/run/mongodb --config /etc/mongod.conf --shutdown
fi

mkdir -p /tmp/state
touch /tmp/state/20-mongo-finish
